name: Android Build
on:
    workflow_dispatch:
    pull_request:
      types:
        - opened
      branches:
        - 'main'
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: |
          npm install
  build-android-apk:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Set up our JDK environment # setup JDK environment: mandatory as we need to build  android project
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
            
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release APK
        run: |
          cd android && ./gradlew assembleRelease
      - name: Build Android Release AAB
        run: |
          cd android && ./gradlew bundleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.aab
          path: android/app/build/outputs/bundle/release/
